"""
Ausgewählte Probleme aus dem ACM Programming Contest  WS21/22 

Problem:  Marko
Link:     https://open.kattis.com/contests/nytf6n/problems/marko

@author   Anton Roesler (anton.roesler@stud.fra-uas.de) 
@version  1.0, 19.12.2021

Method :  Ad-Hoc 
Status :  Accepted
Runtime:  0.11 s

"""



keyboard = {'a': 2, 'b': 2, 'c': 2, 'd': 3, 'e': 3, 'f': 3, 'g': 4, 'h': 4, 'i': 4, 'j': 5, 'k': 5, 'l': 5, 'm': 6, 'n': 6, 'o': 6, 'p': 7, 'q': 7, 'r': 7, 's': 7, 't': 8, 'u': 8, 'v': 8, 'w': 9, 'x': 9, 'y': 9, 'z': 9}


def translate_to_digits(word: str) -> int:
    """
    Translates a word to a number.
    """
    total = ""
    for letter in word:
        total += str(keyboard[letter])
    return int(total)


# Read number of words
N = int(input())

# Read words
words = []  
for i in range(N): 
    words.append(input())

words = sorted(words)

# Read the number that is typed
T = int(input())

# Count how many words are generated by that number
c = 0
for word in words:
    if translate_to_digits(word) == T:
        c += 1

print(c)